name: Publish Poll Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-job-image

on:
  push:
    paths:
      - 'apps/job/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build the project
        run: yarn build
        working-directory: ./apps/job
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/job
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
